# Generated by Django 5.2.1 on 2025-05-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_submission_assignment_and_more'),
        ('api', '0003_initial'),
    ]

    operations = [
    ]
