# Generated by Django 5.2.1 on 2025-06-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='color',
        ),
        migrations.RemoveField(
            model_name='fixedclassschedule',
            name='class_type',
        ),
        migrations.AddField(
            model_name='fixedclassschedule',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
