# Generated by Django 5.2.1 on 2025-06-13 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_course_options_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
