# Generated by Django 5.2.1 on 2025-06-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], default='fall', max_length=20),
        ),
    ]
