# Generated by Django 5.2.1 on 2025-06-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_semester_semester_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], max_length=20),
        ),
    ]
