# Generated by Django 5.2.1 on 2025-06-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userprofile_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['academicLevel', 'code']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='level',
            new_name='academicLevel',
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(blank=True, choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], max_length=10, null=True),
        ),
    ]
