# Generated by Django 5.2.1 on 2025-06-22 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedclassschedule',
            name='semester',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_schedules', to='api.semester'),
        ),
        migrations.AddField(
            model_name='studyblock',
            name='semester',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='api.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
