# Generated by Django 5.2.1 on 2025-06-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_fixedclassschedule_semester_studyblock_semester_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedclassschedule',
            old_name='location',
            new_name='difficulty_level',
        ),
    ]
