# Generated by Django 5.2.1 on 2025-06-24 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_location_fixedclassschedule_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedclassschedule',
            name='day',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='fixedclassschedule',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_schedules', to='api.semester'),
        ),
    ]
