# Generated by Django 5.2.1 on 2025-06-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fileupload_group_message_messagecontent_and_more'),
        ('api', '0018_alter_studyblock_options_and_more'),
    ]

    operations = [
    ]
