version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - appnet

  backend:
    build:
      context: ./backend
    command: ["./entrypoint.sh"]
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=backend.backend.settings
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb
      - ALLOWED_HOSTS=*
    depends_on:
      - db
    networks:
      - appnet
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - appnet
    ports:
      - "80:80"

volumes:
  postgres_data:

networks:
  appnet:
    driver: bridge 