# Generated by Django 5.2.1 on 2025-06-04 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_semester_course_userpreferences_fixedclassschedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedclassschedule',
            name='location',
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Very Hard')], default=2),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='study_start_min',
            field=models.TimeField(default='20:00', help_text='Earliest preferred study start time'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('minor', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('level', models.CharField(default='Undergraduate', max_length=20)),
                ('profile_picture', models.FilePathField(blank=True, null=True, path='profile_pictures/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
